name: FakePluginsCommand
version: '${project.version}'
main: com.ashkiano.fakepluginscommand.FakePluginsCommand
api-version: '1.16'
commands:
  plugins:
    description: Displays fake plugins list
    usage: /<command>
    aliases: [pl]